import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BoxLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.*;
import javax.swing.plaf.ColorUIResource;

public class GUI_1 {
    public GUI_1() {
        ImageIcon img = new ImageIcon("d:\\java\\jpotify\\icon.png");
        JFrame Jpotify = new JFrame("Jpotify");
        Jpotify.setResizable(false);
        Jpotify.setIconImage(img.getImage());
        Jpotify.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        Jpotify.setLocation(700, 375);
        Jpotify.setLayout(new BorderLayout());
        JPanel start = new JPanel();
        start.setLayout(new BorderLayout());
        start.setBackground(Color.cyan);
        JPanel panele = new JPanel();
        panele.setLayout(new BorderLayout());
        panele.setBackground(Color.cyan);
        JPanel panelw = new JPanel();
        panelw.setLayout(new BorderLayout());
        panelw.setBackground(Color.cyan);
        JPanel panels = new JPanel();
        panels.setLayout(new BorderLayout());
        panels.setBackground(Color.cyan);
        JPanel panelc = new JPanel();
        panelc.setLayout(new BorderLayout());
        panelc.setBackground(Color.CYAN);
        JPanel panelcw = new JPanel();
        panelcw.setLayout(new BorderLayout());
        panelcw.setBackground(Color.cyan);
        JPanel panelce = new JPanel();
        panelce.setLayout(new BorderLayout());
        panelce.setBackground(Color.cyan);
        JPanel panelsc = new JPanel();
        panelsc.setLayout(new BorderLayout());
        panelsc.setBackground(Color.cyan);
        JPanel panelsw = new JPanel();
        panelsw.setLayout(new BorderLayout());
        panelsw.setBackground(Color.cyan);
        JPanel panelse = new JPanel();
        panelse.setLayout(new BorderLayout());
        panelse.setBackground(Color.cyan);
        start.add(panelw, BorderLayout.WEST);
        panelw.add(new JLabel("Username:  "), BorderLayout.NORTH);
        panelw.add(new JLabel("Password:  "), BorderLayout.SOUTH);
        start.add(panelc, BorderLayout.CENTER);
        panelc.add(panelcw, BorderLayout.WEST);
        JTextField Userup = new JTextField();
        Userup.setBackground(Color.YELLOW);
        panelcw.add(Userup, BorderLayout.NORTH);
        JPasswordField Passup = new JPasswordField();
        Passup.setBackground(Color.YELLOW);
        Passup.setEchoChar('*');
        panelcw.add(Passup, BorderLayout.SOUTH);
        panelce.add(new JLabel("Username:  "), BorderLayout.NORTH);
        panelce.add(new JLabel("Password:  "), BorderLayout.SOUTH);
        JLabel J = new JLabel("Jpotify");
        J.setFont(new Font("Serif", Font.BOLD, 50));
        J.setForeground(Color.YELLOW);
        J.setHorizontalAlignment(SwingConstants.CENTER);
        panelc.add(J, BorderLayout.CENTER);
        panelc.add(panelce, BorderLayout.EAST);
        start.add(panele, BorderLayout.EAST);
        JTextField Userin = new JTextField();
        Userin.setBackground(Color.YELLOW);
        panele.add(Userin, BorderLayout.NORTH);
        JPasswordField Passin = new JPasswordField();
        Passin.setBackground(Color.YELLOW);
        Passin.setEchoChar('*');
        panele.add(Passin, BorderLayout.SOUTH);
        start.add(panels, BorderLayout.SOUTH);
        panels.add(panelsc, BorderLayout.CENTER);
        JButton Signup = new JButton("Signup");
        Signup.setBackground(Color.GREEN);
        panelsc.add(Signup, BorderLayout.WEST);
        JButton Signin = new JButton("Signin");
        Signin.setBackground(Color.GREEN);
        panelsc.add(Signin, BorderLayout.EAST);
        panels.add(panelsw, BorderLayout.WEST);
        panelsw.add(new JLabel("                       "));
        panels.add(panelse, BorderLayout.EAST);
        panelse.add(new JLabel("    "));
        panelcw.add(new JLabel("                           "), BorderLayout.WEST);
        panele.add(new JLabel("                           "), BorderLayout.EAST);
        Jpotify.add(start);
        Jpotify.setVisible(true);
        Jpotify.pack();
    }

}